 select count(*) sberbank_not_null from sentirus.bank_train_2016 where not sberbank is null;
 select count(*) sberbank_positive from sentirus.bank_train_2016 where sberbank=1;
 select count(*) sberbank_negative from sentirus.bank_train_2016 where sberbank=-1;
 select count(*) sberbank_neutral from sentirus.bank_train_2016 where sberbank=0;
 select count(*) vtb_not_null from sentirus.bank_train_2016 where not vtb is null;
 select count(*) vtb_positive from sentirus.bank_train_2016 where vtb=1;
 select count(*) vtb_negative from sentirus.bank_train_2016 where vtb=-1;
 select count(*) vtb_neutral from sentirus.bank_train_2016 where vtb=0;
 select count(*) gazprom_not_null from sentirus.bank_train_2016 where not gazprom is null;
 select count(*) gazprom_positive from sentirus.bank_train_2016 where gazprom=1;
 select count(*) gazprom_negative from sentirus.bank_train_2016 where gazprom=-1;
 select count(*) gazprom_neutral from sentirus.bank_train_2016 where gazprom=0;
 select count(*) alfabank_not_null from sentirus.bank_train_2016 where not alfabank is null;
 select count(*) alfabank_positive from sentirus.bank_train_2016 where alfabank=1;
 select count(*) alfabank_negative from sentirus.bank_train_2016 where alfabank=-1;
 select count(*) alfabank_neutral from sentirus.bank_train_2016 where alfabank=0;
 select count(*) bankmoskvy_not_null from sentirus.bank_train_2016 where not bankmoskvy is null;
 select count(*) bankmoskvy_positive from sentirus.bank_train_2016 where bankmoskvy=1;
 select count(*) bankmoskvy_negative from sentirus.bank_train_2016 where bankmoskvy=-1;
 select count(*) bankmoskvy_neutral from sentirus.bank_train_2016 where bankmoskvy=0;
 select count(*) raiffeisen_not_null from sentirus.bank_train_2016 where not raiffeisen is null;
 select count(*) raiffeisen_positive from sentirus.bank_train_2016 where raiffeisen=1;
 select count(*) raiffeisen_negative from sentirus.bank_train_2016 where raiffeisen=-1;
 select count(*) raiffeisen_neutral from sentirus.bank_train_2016 where raiffeisen=0;
 select count(*) uralsib_not_null from sentirus.bank_train_2016 where not uralsib is null;
 select count(*) uralsib_positive from sentirus.bank_train_2016 where uralsib=1;
 select count(*) uralsib_negative from sentirus.bank_train_2016 where uralsib=-1;
 select count(*) uralsib_neutral from sentirus.bank_train_2016 where uralsib=0;
 select count(*) rshb_not_null from sentirus.bank_train_2016 where not rshb is null;
 select count(*) rshb_positive from sentirus.bank_train_2016 where rshb=1;
 select count(*) rshb_negative from sentirus.bank_train_2016 where rshb=-1;
 select count(*) rshb_neutral from sentirus.bank_train_2016 where rshb=0;

